### ISSUE TITLE
The example uses deprecated `loop` parameter of web.Application

### ISSUE THREAD

**Issue by gthb** [aio-libs/pytest-aiohttp#13]
The example in the README calls `web.Application(loop=loop)`, which is [deprecated since aiohttp 3.5](https://docs.aiohttp.org/en/stable/web_reference.html#aiohttp.web.Application.loop).

**Comment by asvetlov** [comment]
Would you provide a PR with README fix?

**Comment by gthb** [comment]
I would, but I don't know for sure what the fix should be :-) because this is trying to make things “just work” with magic behind the scenes, and documentation is scant. After a bit of trial and error I got my own use case working like so:

```python
from aiohttp import ClientResponse
import pytest
from myactualcode import create_app

@pytest.fixture()
def client(loop, aiohttp_client):
    return loop.run_until_complete(aiohttp_client(create_app()))

async def test_stuff(client):
    resp: ClientResponse = await client.get("/stuff")
    assert resp.status == 200
    [go on asserting things]
```

... and _maybe_ that's the intended way to use this, but I'm new to `pytest` _and_ `asyncio` _and_ `aiohttp` so I can't tell for sure.

**Comment by gyermolenko** [comment]
My suggestion is:
- remove the loop
- substitute `test_client` with `aiohttp_client`

[this](https://github.com/aio-libs/aiohttp/blob/master/tests/test_pytest_plugin.py#L29-L40) might help.

**Comment by asvetlov** [comment]
Fixed
