### ISSUE TITLE
pytest-aiohttp is incompatible with pytest-asyncio v0.14.0

### ISSUE THREAD

**Issue by Carsten-Leue** [aio-libs/pytest-aiohttp#16]
When running `pytest-aiohttp` with `pytest-asyncio` v0.14.0 I am seeing the following error:

```
RuntimeError: Timeout context manager should be used inside a task
```

This is related to a change in `pytest-asyncio` concerning event loop handling (see https://github.com/pytest-dev/pytest-asyncio/issues/170). Explanation in https://github.com/pytest-dev/pytest-asyncio/issues/170#issuecomment-650583848

Would it be possible to coordinate with the `pytest-asyncio` team so both your awesome libraries can be used at the same time.

**Comment by asvetlov** [comment]
Fixed
