### ISSUE TITLE
asyncio_mode deprecation warning is emitted for test suites that don't use aiohttp at all

### ISSUE THREAD

**Issue by mgorny** [aio-libs/pytest-aiohttp#38]
When pytest-aiohttp plugin is installed, practically every single test suite on my system emits the following deprecation warning:

```pytb
========================================================== warnings summary ===========================================================
../../../../../../../../usr/lib/python3.8/site-packages/pytest_aiohttp/plugin.py:28
  /usr/lib/python3.8/site-packages/pytest_aiohttp/plugin.py:28: DeprecationWarning: The 'asyncio_mode' is 'legacy', switching to 'auto'
 for the sake of pytest-aiohttp backward compatibility. Please explicitly use 'asyncio_mode=strict' or 'asyncio_mode=auto' in pytest co
nfiguration file.
    config.issue_config_time_warning(LEGACY_MODE, stacklevel=2)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

In the best case, this is meaningless since the vast majority of these packages don't use aiohttp at all, and therefore shouldn't be setting `asyncio_mode` in the first place. In the worst, it causes test failures for various packages that expect specific pytest output, in particular pytest plugins.

**Comment by seifertm** [comment]
This is probably best addressed in pytest-asyncio.

Related issue:
https://github.com/pytest-dev/pytest-asyncio/issues/293

**Comment by mgorny** [comment]
I agree. It's been reported a long time ago but unfortunately there's very little we can do at this point. I mean, I'm pretty sure you can imagine the fallout if plugins suddenly started needing to be enabled explicitly.

Hmm, I wonder if patching pytest-asyncio to default to auto would break stuff…

**Comment by mgorny** [comment]
Unfortunately, using a virtualenv doesn't guarantee that the project will actually work in the production environment. The only way to do that is to run tests in exactly the same environment as the actual package will run.

**Comment by Dreamsorcerer** [comment]
I think another option would be to uninstall pytest-aiohttp, and use aiohttp.pytest_plugin explicitly. This seems to be what core aiohttp itself does: https://github.com/aio-libs/aiohttp/blob/master/tests/conftest.py#L31
