### ISSUE TITLE
Follow PEP 561 to support type checking with mypy

### ISSUE THREAD

**Issue by MHajoha** [aio-libs/pytest-aiohttp#40]
Tests using pytest-aiohttp cannot be completely typechecked using [mypy](https://mypy.readthedocs.io/en/stable/index.html) because it lacks the `py.typed` marker file and no separate stubs exist in PyPI.

This page details how a package can be made PEP 561 compatible, allowing mypy to check its usages: https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

**Comment by Dreamsorcerer** [comment]
The library isn't even imported as a user. How would this be useful?

If you're using the aiohttp fixtures, and want to annotate them in your test functions, just import from aiohttp itself. For example:
https://github.com/aio-libs/aiohttp/pull/6555/files#diff-8cadf0d03b326ef5c8ff78864d1f60294e73a78f3ffaaefaf7ef60d1a909ea7bR162

**Comment by MHajoha** [comment]
Thanks for the hint. I wasn't aware `AiohttpClient` was duplicated in `aiohttp.pytest_plugin`. What exactly is the difference between it and `pytest_aiohttp.plugin` then?

**Comment by Dreamsorcerer** [comment]
The code duplication seems to have happened when moving to using pytest-asyncio though: https://github.com/aio-libs/pytest-aiohttp/pull/19
