### ISSUE TITLE
PytestDeprecationWarning with pytest 7.2.0

### ISSUE THREAD

**Issue by frenzymadness** [aio-libs/pytest-aiohttp#47]
This line

https://github.com/aio-libs/pytest-aiohttp/blob/a2c68a89dd6a4f987ad7f826f16491ab96d4916f/pytest_aiohttp/plugin.py#L21

causes

```
pytest.PytestDeprecationWarning: The hookimpl pytest_configure uses old-style configuration options (marks or attributes).
Please use the pytest.hookimpl(tryfirst=True) decorator instead
 to configure the hooks.
 See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
```
with pytest 7.2.0.

**Comment by vitek** [comment]
@danigm it's fixed for a long time in upstream. When will it be fixed in release?

**Comment by danigm** [comment]
> @danigm it's fixed for a long time in upstream. When will it be fixed in release?

I don't know, that depends on the project maintainers.

**Comment by cdce8p** [comment]
@Dreamsorcerer Would you be able to do a new release? The fix was merged 9 months ago and there hasn't been a release since.

**Comment by Dreamsorcerer** [comment]
I don't tend to touch this repo, but will try and bump the version and see if the CI is all good.

**Comment by Dreamsorcerer** [comment]
OK, looks like it worked.

**Comment by cdce8p** [comment]
Awesome! Thanks @Dreamsorcerer 🚀
