### ISSUE TITLE
add option to set default headers

### ISSUE THREAD

**Issue by louisabraham** [aio-libs/pytest-aiohttp#55]
This is really useful when wanting to test against an authenticated endpoint.

the code could look like

```
aiohttp_client(app, headers=headers)
```

**Comment by Dreamsorcerer** [comment]
Wait, this package now duplicates the code from aiohttp and is missing that functionality...

@bdraco @webknjaz Do we want to remove pytest_plugin.py from aiohttp and move all the code here? Seems like that's what @asvetlov was planning (see #2 for example). We'd need to do that in master only as it's also possible for people to have specified the aiohttp.pytest_plugin directly (which is what aiohttp itself does currently).

In the past this package just imported aiohttp-.pytest_plugin.
