### ISSUE TITLE
Expose types and add py.typed marker

### ISSUE THREAD

**Issue by netrix** [aio-libs/pytest-aiohttp#59]
It looks like this library is fully typed but these types are not exposed to users. Can you provided types in `__init__.py` and add `py.typed` marker?

**Comment by asvetlov** [comment]
Good question.
Basically we import types from `aiohttp.pytest_plugin` but exposing them directly by `pytest-aiohttp` makes sense to me.
A champion for corresponding PR is welcome!

**Comment by Dreamsorcerer** [comment]
> Basically we import types from `aiohttp.pytest_plugin`

Actually, you stopped doing that several years ago, and copied the code to this repo. This has lead to the code coming out-of-sync. I recently synced it in #56.

As per https://github.com/aio-libs/pytest-aiohttp/issues/55#issuecomment-2388567842 would you like to proceed with removing/deprecating aiohttp.pytest_plugin? Maintaining 2 copies of the code is not going to work long-term.

**Comment by asvetlov** [comment]
> As per https://github.com/aio-libs/pytest-aiohttp/issues/55#issuecomment-2388567842 would you like to proceed with removing/deprecating aiohttp.pytest_plugin? Maintaining 2 copies of the code is not going to work long-term.

Yes, I agree. 
We can add `__dir__` and `__getattr__` to `aiohttp.pytest_plugin` that will return names from `pytest_aiohttp` with raising a deprecation warning.
