### ISSUE TITLE
every test run twice: pyloop and uvloop

### ISSUE THREAD

**Issue by Stamper** [aio-libs/pytest-aiohttp#7]
hello! help me, please

my aiohttp application works with uvloop
`asyncio.set_event_loop_policy(uvloop.EventLoopPolicy())`
`loop = asyncio.get_event_loop()`

surprisingly every pytest test runs twice: with uvloop and pyloop
```
@fixture
def client(loop, test_client):
    app = init_app(loop)
    return loop.run_until_complete(test_client(app))

async def test_get(client):
    response = await client.get('v1/accounts/{}'.format(ACCOUNT_ID))
    assert response.status == 200
```
why?

**Comment by asvetlov** [comment]
Because it runs tests against standard asyncio loop and uvloop is the latter is installed.
I don't say it's the best possible approach but explain current behavior.

**Comment by Stamper** [comment]
@asvetlov thank you! could you advise me how I can avoid it?

**Comment by asvetlov** [comment]
You may add a custom `loop` fixture into your `conftest.py`.
It should override default one AFAIK.

**Comment by Stamper** [comment]
thank you!
